language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1.5
  - jruby
  - ruby-head

script: "bundle exec rspec spec/"

notifications:
  - paulopatto@gmail.com

addons:
  code_climate:
    repo_token:
